[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[[redirects]]
  from = "/dreamforce"
  to = "https://tools.smartwinnr.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}