# baseURL = "https://smartwinnr/help/"
# baseURL = "https://smartwinnr-help.netlify.com/"
baseurl = "/"

languageCode = "en-us"
title = "SmartWinnr"
theme = "docsmith"

# Highlighting config (Pygments)

# Styles created with hugo gen chromastyles --style=perldoc > assets/stylesheets/_syntax-chroma.css
pygmentsUseClasses =  true
pygmentsCodeFences = true

# Use the new and fast Chroma highlighter (Pygments port) in Hugo >= 0.28.
pygmentsUseClassic = false

# See https://help.farbox.com/pygments.html
# Also see pygmentsUseClasses above.
pygmentsStyle = "perldoc"

disqusShortname="smartwinnr"

# disableKinds = ["taxonomy", "taxonomyTerm"]

rssLimit = 15

[blackfriday]
fractions = false

[outputs]
home = [ "HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Smartwinnr: Gamified knowledge to drive performance"
default_image_width = 120
default_image_height = 120
# custom_css = ["../stylesheets/icomoon.css", "../stylesheets/home.css"]

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_default = "Monday, January 2, 2006"


# Related Content ("See Also") configuration.
[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

# Google Roboto fonts
# googlefonts = "//fonts.googleapis.com/css?family=Roboto:400"
